### ISSUE TITLE
Update gym to gymnasium

### ISSUE THREAD

**Issue by gcroci2** [ANNUBS/neurogym#1]
The team that has been maintaining Gym since 2021 has moved all future development to [Gymnasium](https://github.com/Farama-Foundation/Gymnasium), a drop in replacement for Gym, and Gym will not be receiving any future updates. The recommendation is to switch to Gymnasium.

To know more about the story behind this switch, check out [this blog post](https://farama.org/Announcing-The-Farama-Foundation).

**Comment by DaniBodor** [comment]
finished in #7
