### ISSUE TITLE
Understand how data are generated

### ISSUE THREAD

**Issue by gcroci2** [ANNUBS/neurogym#3]
Taking as example `GoNogo` env class, we want to understand how the signals are generated. Starting from the 4 plots plotted via  `plotting.plot_env` could be a good starting point.

**Comment by DaniBodor** [comment]
There's literally a file called "examples/understanding_neurogym_task.ipynb" 😆

**Comment by gcroci2** [comment]
> There's literally a file called "examples/understanding_neurogym_task.ipynb" 😆

Seen now LOL
